### ISSUE TITLE
Translate A.08-minecraft-vj.md

### ISSUE THREAD

**Issue by ghost** [RomanSaveljev/sonic-pi#49]

**Comment by RomanSaveljev** [comment]
Ура! Последний остался!!

**Comment by ghost** [comment]
О, да. Но что-то тяжеловато даётся.

**Comment by RomanSaveljev** [comment]
Я знаю.. Очень тяжело переводить из-за того, что сам текст оригинала довольно примитивный. Без конца повторяются одни и те же слова и обороты - я замучился синонимы подбирать

**Comment by ghost** [comment]
Да и под конец стали попадаться такие обороты, значение которых я никак не могу понять (в первых двух абзацах). Может быть это такой сленг...
