### ISSUE TITLE
Optimization of the translated chapters. 

### ISSUE THREAD

**Issue by ghost** [RomanSaveljev/sonic-pi#50]
# Optimization of the translated chapters.

Since different chapters of the tutorial were translated by different people, the same concepts may be translated differently. It is therefore Necessary to check the translated texts and GUI, and bring them to a single mind. 

As this issue refers to the specificities of translation, further discussion, let's be in Russian language. 
## Нужен совет:

Как лучше/правильнее перевести: 
- **Run** - Выолнить или Запустить? 
- **You** - Ты или Вы? Я считаю, что правильнее "Вы", т.к. это позволяет избежать конфликтов c половой принадлежностью читателя и это более уважительно, но , также и более "официально"... 
- **Thread** - поток. Но в начале я переводил это как нить... 
- **Live coding** - живое кодирование звучит как-то не очень... Может быть, правильнее будет "Лайв кодинг"? 

В ходе проверки, скорее всего, появятся ещё вопросы подобного плана.

**Comment by RomanSaveljev** [comment]
I think this is a great idea to make the terminology consistent throughout the text. Here is my comments:

> Run - Выолнить или Запустить?

По-моему, я переводил и так, и так..

> You - Ты или Вы?

Переводил как "ты" и глаголы употреблял в мужском роде. По тексту полно оборотов типа "ну же, пора поиграть" - официальное обращение как-то не вяжется.. Третий вариант: явно использовать везде множественное число и обращаться как бы к аудитории, а не к конкретному читателю.

> Thread - поток

Я бы так и переводил. Нить уж как-то совсем по-ботански звучит. Если перевод не дает явного контекста, то можно уточнять "поток исполнения".

> Live coding - живое кодирование

Тут я пытался провести аналогии с "live performance" - "живое исполнение". По тексту сделанного перевода также употребляется "кодирование вживую". Можно поменять на "лайв кодинг" или еще какое производное, если так по-вашему лучше.

P.S. Лучшее - враг хорошего :)

**Comment by ghost** [comment]
Спасибо за совет! Особенно про лучшее - враг хорошего )))

**Comment by ghost** [comment]
Какое лучше использовать местоимение для "Sonic Pi"?
"Она" - программа, "Он" - соник?, Или "Это"?

**Comment by RomanSaveljev** [comment]
Грепом быстренько прошелся по переводу - вроде бы я использовал "он".

Он - продукт, инструмент - наверное такая логика была..

**Comment by ghost** [comment]
Ещё возник вопрос. Вы не будете против, если я переформулирую некоторые из переведённых Вами фраз (в целях улучшения читабельности)?

**Comment by RomanSaveljev** [comment]
Да, пожалуйста. Некоторые вещи явно мной в каком-то бреду переводились. Так что любые необходимые исправления приветствуются. А заодно и перевод к единому стилю придет

**Comment by ghost** [comment]
Ок, спасибо.
